# Generated by Django 5.0.1 on 2024-01-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('area', models.FloatField()),
            ],
        ),
    ]
