# Generated by Django 5.0.1 on 2024-01-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_apartmentbuildingplace_remove_admin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='server.userprofile'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='server.userprofile'),
        ),
    ]
