# Generated by Django 5.0.1 on 2024-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_apartmentbuilding_admin_remove_post_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
    ]
